name: Java CI with Maven

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn exec:java -Dexec.mainClass="net.sf.saxon.Transform" -Dexec.args="-xsl:src/main/resources/xsl/main.xsl -it"
    - name: Build with Maven Saxon 11
      run: mvn exec:java -Dsaxon.version=11.6 -Dexec.mainClass="net.sf.saxon.Transform" -Dexec.args="-xsl:src/main/resources/xsl/main.xsl -it"
